### ISSUE TITLE
getlogin not working on windows

### ISSUE THREAD

**Issue by tyeeman** [wmark/thot#3]
Just installed and trying to create quickstart site and I get this error-

```  
File "G:\Program Files\Python2711\lib\site-packages\thot-1.2.0-py2.7.egg\thot\app.py", line 6, in
<module>
    from os import makedirs, getcwd, getlogin
ImportError: cannot import name getlogin
```
Any tips?

**Comment by wmark** [comment]
There's so much missing in your bug report. For example, what flavour of Python do you use? *ActivePython*?

What did you do to diagnose the issue? Did you find `getlogin` in a different package/module?

`from os import getlogin` succeeds using *CPython* v2.7.13 for me on Windows 10.

**Comment by tyeeman** [comment]
As you can see by the path to Python, I'm using 2.7.11. It's just the python download for windows from python.org. I'm using Windows 7 also. I read some troubleshooting steps from stackoverflow about searching os.py for getlogin, so I did but it's not found. Should it be?

**Comment by wmark** [comment]
The version you obtained from Python.org is the regarded as the »reference implementation«. It should come with `os.getlogin`, and does with v2.7.13. Re-install/upgrade is my recommendation.

As this is no error in *thot* I am closing this issue now.
